"""Initial tooling workflow schema

Revision ID: 0001
Revises:
Create Date: 2026-09-15 11:46:10.038842

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("pn", sa.String(length=128), nullable=False),
        sa.Column("desc", sa.String(length=255), nullable=False),
        sa.Column("plant", sa.String(length=128), nullable=True),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column("cur", sa.String(length=128), nullable=True),
        sa.Column("nw", sa.String(length=128), nullable=True),
        sa.Column("po", sa.String(length=128), nullable=True),
        sa.Column("tag", sa.String(length=128), nullable=True),
        sa.Column("too_owner", sa.String(length=128), nullable=True),
        sa.Column("cav", sa.String(length=64), nullable=True),
        sa.Column("saving", sa.String(length=128), nullable=True),
        sa.Column("oem", sa.String(length=128), nullable=True),
        sa.Column("tech", sa.String(length=128), nullable=True),
        sa.Column("bu", sa.String(length=128), nullable=True),
        sa.Column("owner", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.Date(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_projects_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_projects_pn"), ["pn"], unique=False)

    op.create_table(
        "project_actions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("ph", sa.Integer(), nullable=False),
        sa.Column("tab", sa.String(length=128), nullable=False),
        sa.Column("act", sa.String(length=255), nullable=False),
        sa.Column("input_type", sa.String(length=128), nullable=False),
        sa.Column("fn", sa.String(length=64), nullable=False),
        sa.Column("owner", sa.String(length=128), nullable=True),
        sa.Column("dep_id", sa.String(length=64), nullable=True),
        sa.Column("lead_default", sa.Integer(), nullable=True),
        sa.Column("lead", sa.Integer(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("done_date", sa.Date(), nullable=True),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("link", sa.String(length=255), nullable=True),
        sa.Column("is_custom", sa.Boolean(), nullable=False),
        sa.Column("last_remind_date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("project_actions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_project_actions_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_project_actions_ph"), ["ph"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_project_actions_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "team_members",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("function", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("email", sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("team_members", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_team_members_project_id"), ["project_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("team_members", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_team_members_project_id"))

    op.drop_table("team_members")
    with op.batch_alter_table("project_actions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_project_actions_project_id"))
        batch_op.drop_index(batch_op.f("ix_project_actions_ph"))
        batch_op.drop_index(batch_op.f("ix_project_actions_id"))

    op.drop_table("project_actions")
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_projects_pn"))
        batch_op.drop_index(batch_op.f("ix_projects_id"))

    op.drop_table("projects")
    # ### end Alembic commands ###
